### ISSUE TITLE
Challenge 5 - Infrastructure as Code

### ISSUE THREAD

**Issue by pamelasarkisyan** [what-the-hack-event/wth-team9#4]
https://colinbeales.github.io/WhatTheHack/031-DevOpsWithGitHub/Student/challenge05.html

**Comment by darthaaron** [comment]
thanks pam!

**Comment by ShresthaRajat** [comment]
Use this for sharing codes

https://docs.google.com/document/d/11063QFXRiHEx9WfaFVZzW16GFbK_sa3ECwSIz7MF0uw/edit?usp=sharing

**Comment by pamelasarkisyan** [comment]
https://github.com/what-the-hack-event/wth-team9/blob/main/.github/workflows/deploy.yml
